### PR TITLE
add a build.sh and make hashbangs work

### PR DESCRIPTION
**Pull request by gordallott**

### CODE REVIEW

**Comment by gordallott** [comment]
checks pass so it must be fine

**Comment by gordallott** [comment]
added another bit of code to check for collaborated users before building pr's, owners count as collaborators but it means if we ever get non building pr's, first point of call should be to check whoever it is counts as a collaborator in the repository

**Comment by gordallott** [comment]
hey look at that it even fails right

**Comment by njpatel** [comment]
I like it a lot. 👍

**Pull request merged**
